### ISSUE TITLE
Google now accepts zips with a key in their manifest

### ISSUE THREAD

**Issue by bcg-robert-cambridge** [Zensight/extensionator#4]
http://www.rubydoc.info/gems/extensionator/
> `--inject-key`. If you have an extension in the store, you know you can't have a "key" property in your manifest file

I know this used to be the case but it no longer appears to be true - I just uploaded a zip with a key in its manifest and no errors were thrown.

**Comment by icambron** [comment]
Oh cool. Good to know. I'll update the docs and deprecate the option.

**Comment by icambron** [comment]
Added a note to the Readme about this and other important-to-know changes about Chrome
